server:
  port: 9001   # default port is 8761 for Eureka Server

spring:
 application:
  name: service-registry
# servlet:
#  context-path: /eureka
   
eureka:
  client:
    register-with-eureka: false  # server doesn\u2019t register itself
    fetch-registry: false        # server doesn\u2019t fetch registry
  server:
    wait-time-in-ms-when-sync-empty: 0
    
# ===============================
# Acutator -log Info
# ===============================
management:
 endpoints:
  web:
   base-path: /sysAdmin
   exposure:
    include: health,info,logfile,beans,heapdump
 endpoint:
  gateway:
   enabled: true
  health:
   show-details: always
