spring:
 application.name: customer-service
 profiles:
  active: dev
  
server:
 port: 9012
 servlet:
  context-path: /Customer
  
 rabbitmq:
  listener:
   simple:
    default-requeue-rejected: false
  message-converter:
   json:
    trusted-packages: com.relx.banking,java.util,java.lang

