server:
 port: 9011
 servlet:
  context-path: /config
 
spring:
 application:
  name: bank-config-service
 profiles:
  active: dev
# security:
#  oauth2:
#   resourceserver:
#    jwt:
#     issuer-uri: http://localhost:9003  # same as auth-service
# 
 rabbitmq:
  listener:
   simple:
    auto-startup: false   # prevents listener from starting too early


