# ===============================
# If Override properties
# ===============================
#spring:
# cloud:
#  config:
#   allowOverride: true
#   overrideNone: true
#   overrideSystemProperties: false

# ===============================
# Eureka discovery client 
# ===============================
eureka:
 client:
  service-url:
   defaultZone: http://localhost:9001/eureka/
# ===============================
# Datasource
# ===============================
spring:
 datasource:
  hikari:
   minimum-idle: 5
   maximum-pool-size: 20
   idle-timeout: 30000
   pool-name: NeonHikariCP
   maxLifetime: 1800000
   connectionTimeout: 20000
   transaction-isolation: TRANSACTION_READ_COMMITTED
# ===============================
# JPA / HIBERNATE
# ===============================
 jpa:
  database: default
  hibernate:
   ddl-auto: none
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    format_sql: true 
# ===============================
# RabbitMQ Listener
# ===============================   
 rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest 

config:
 init:
  wait:
   attempts: 3
   ms: 1000

# ===============================
# Other Service -url
# ===============================
auth-server:
  url: http://localhost:9003/Auth
api-gateway:
  url: http://localhost:9004  
config-service:
  url: http://localhost:9011/config
customer-service:
  url: http://localhost:9012/Customer
account-service:
  url: http://localhost:9013/Account


# ===============================
# Acutator -log Info
# ===============================
management:
 endpoints:
  web:
   base-path: /sysAdmin
   exposure:
    include: health,info,logfile,beans,heapdump
 endpoint:
  gateway:
   enabled: true
  health:
   show-details: always
   
#================================
# Allow Cross-Origins
#================================  
cross:
 url: "*"

#================================
# Swagger-UI
#================================ 
springdoc:
 api-docs:
  enabled: true
  path: /v3/api-docs
  title: "Bank Application"
  description: "Bank-app Service - Execute document"
  #version: 1.0.0
 swagger-ui:
  enabled: true
  path: /swagger-ui/index.html
  

